version: '3.8'

services:
  currency-exchange:
    image: sagarsd5687/currency-exchange-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - currency-network

networks:
  currency-network:      