INSERT INTO CURRENCY_EXCHAGE (ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MUNTIPLE, ENVIRONMENT)
VALUES(1001, 'USD', 'INR', 65, '');
INSERT INTO CURRENCY_EXCHAGE (ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MUNTIPLE, ENVIRONMENT)
VALUES(1002, 'EUR', 'INR', 95, '');
INSERT INTO CURRENCY_EXCHAGE (ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MUNTIPLE, ENVIRONMENT)
VALUES(1003, 'AUD', 'INR', 45, '');
